### ISSUE TITLE
关于“rec_keys_path”的设置以及“character_dict_path should not be None”这个报错的请教

### ISSUE THREAD

**Issue by puresky123** [Gmgge/ImageAnalysisService#13]
大佬您好，首先感谢您的项目对印章OCR做的贡献。
我是这方面的新手，想在您的项目上通过添加onnx推理模型先体验一下，我参考您在core/ocr/config.yaml文件中的配置信息从PaddleOCR上面下载了ch_PP-OCRv3_det_infer.onnx，ch_ppocr_mobile_v2.0_cls_infer.onnx和ch_PP-OCRv3_rec_infer.onnx这三个模型，然后运行了ocr_system.py文件想测试一下我下载的模型是否兼容您的项目。然后出现下面的报错：
Traceback (most recent call last):
  File "E:/pythonProject/ImageAnalysisService/core/ocr/ocr_system.py", line 190, in <module>
    engine = OCR()
  File "E:/pythonProject/ImageAnalysisService/core/ocr/ocr_system.py", line 30, in __init__
    self.text_rec = TextRecognizer(module_args["Rec"])
  File "E:\pythonProject\ImageAnalysisService\libs\ocr_onnxruntime\ch_ppocr_v3_rec\text_recognize.py", line 39, in __init__
    self.postprocess_op = CTCLabelDecode(character_dict_path)
  File "E:\pythonProject\ImageAnalysisService\libs\ocr_onnxruntime\ch_ppocr_v3_rec\utils.py", line 13, in __init__
    assert character_dict_path is not None, "character_dict_path should not be None"
AssertionError: character_dict_path should not be None
我发现问题出在libs/ocr_onnxruntime/ch_ppocr_v3_rec/text_recognize.py这个文件中self.session.have_key()的值为false，然后core/ocr/config.yaml文件中缺少"rec_keys_path"这一项的设置导致character_dict_path默认取了None
请问大佬"rec_keys_path"需要怎么设置，以及该路径下存储的文件我可以在什么地方获取
还有就是想请教大佬什么模型和您的picodet_s_416_coco_sim.onnx模型的输出是一致的。我在PaddleDetection下载的模型picodet_s_416_coco_lcnet.onnx的推理结果和您后续的处理步骤有冲突。我会自己找模型去训练，麻烦大佬指个路。
感谢大佬，祝您身体健康，万事如意！

**Comment by Gmgge** [comment]
你是否根据分享的印章检测数据集训练了模型？相对与识别模型，印章检测的训练相对简单。如果不是作为商用目的，你甚至可以半天就可以训练出相关模型，如果你希望自己做检测模型的训练，有任何问题都可以提问。
